image: "ruby:2.5"

# Cache gems in between builds
cache:
  paths:
    - vendor/ruby

before_script:
  - ruby -v  # Print out ruby version for debugging
  - gem install bundler -v "$(grep -A 1 "BUNDLED WITH" Gemfile.lock | tail -n 1)"
  - bundle install -j $(nproc) --path vendor  # Install dependencies into ./vendor/ruby

rubocop:
  script:
    - bundle exec rubocop -v
    - bundle exec rubocop

test:
  script:
    - bundle exec rake test
  artifacts:
    reports:
      cobertura: coverage/coverage.xml
