image: "ruby:2.5"

# Cache gems in between builds
cache:
  paths:
    - vendor/ruby

before_script:
  - ruby -v  # Print out ruby version for debugging
  - bundle install -j $(nproc) --path vendor  # Install dependencies into ./vendor/ruby

rubocop:
  script:
    - bundle exec rubocop -v
    - bundle exec rubocop
